release: test.cpp
	g++ -O0 -std=c++11 test.cpp src/*.cc -I./include -L./lib -lgtest -lpthread -o g++_O0.out

O1: test.cpp
	g++ -O1 -std=c++11 test.cpp src/*.cc -I./include -L./lib -lgtest -lpthread -o g++_O1.out

O2: test.cpp
	g++ -O2 -std=c++11 test.cpp src/*.cc -I./include -L./lib -lgtest -lpthread -o g++_O2.out

O3: test.cpp
	g++ -O3 -std=c++11 test.cpp src/*.cc -I./include -L./lib -lgtest -lpthread -o g++_O3.out